name: Report a bug 🐛
description: Is something broken? Let us know!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Please provide a brief summary of the bug
      description: Please provide a brief summary of the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Please provide steps to reproduce where possible
      description: |
        All bug reports must have steps to reproduce. Otherwise, we cannot work on it! A crash dump is not sufficient!
        
        Please provide a minimal, reproducible example that we can run locally. See
        https://stackoverflow.com/help/minimal-reproducible-example for what that means.
        A public GitHub repository works best. See
        https://github.com/aahlenst/datetimeformatter-parse-bug for a live example.
  - type: textarea
    id: expected
    attributes:
      label: Expected Results
      description: What did you expect to happen?
      placeholder: Tell us what you expected to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Results
      description: What actually happened?
      placeholder: Tell us what actually happened
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Triaging Information"
  - type: input
    id: java-version
    attributes:
      label: What Java Version are you using?
      description: Paste the output of `java --version` in this box
      placeholder: Output of `java --version`
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: What is your operating system and platform?
      description: Please add as much information here as possible including your Operating System, architecture etc.
      placeholder: e.g "Ubuntu 18.04 on ARM64" or "Windows 10 2004 on x86-64"
  - type: textarea
    id: install-method
    attributes:
      label: How did you install Java?
      description: Whether you used a binary archive (zip, tar.gz), an installer package (MSI, rpm, etc.), a version manager (jabba, jenv, etc.).
  - type: textarea
    id: work-before
    attributes:
      label: Did it work before?
      description: Did this work with a previous Java version? If so, please specify what changed.
      render: shell
  - type: textarea
    id: other-versions
    attributes:
      label: Did you test with other Java versions?
      description: |
        Please specify exactly what Java versions you tested with, for example by pasting the output of `java --version`.

        If available, test with a supported build:

          * https://adoptium.net/marketplace
          * http://jdk.java.net/ (anything newer than 8, 11)
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
